[tool.poetry]
name = "hexlet_code"
version = "0.1.0"
description = ""
authors = ["Roddy <per677199@yandex.ru>"]

packages = [
{ include = 'gendiff'},
]


[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"

[tool.poetry.scripts]
gendiff = "gendiff.generate_diff:main"
tests = "tests.test_generate_diff:test"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

