[tool.poetry]
name = "hexlet_code"
version = "0.1.0"
description = ""
authors = ["Roddy <per677199@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
gendiff = "hexlet_code.scripts.gendiff:main"
